
IMPORT OS
IMPORT PANDAS AS PD
IMPORT CONFIG

LS = PD.READ_CSV('PLATE_LIST.CSV').COLUMNS.TOLIST()

FOR FILE IN LS[1:]:
        PRINT(OS.LISTDIR('../'))
        SQLITE = '{}.SQLITE'.FORMAT(FILE)
        CSV = '{}_LOC.CSV'.FORMAT(FILE)
        OS.SYSTEM("AWS S3 CP {} ./".FORMAT(CONFIG.SQL_LOCATION))
        OS.SYSTEM("SQLITE3 -HEADER -CSV {} 'SELECT IMAGE_METADATA_PLATE, IMAGE_METADATA_WELL, IMAGE_METADATA_SITE, NUCLEI_LOCATION_CENTER_X, NUCLEI_L$")
        OS.SYSTEM("AWS S3 CP {} {}".FORMAT(CSV, CONFIG.CSV_LOCATION))
        PRINT("DONE WITH FILE: {}".FORMAT(FILE))
        OS.REMOVE(SQLITE)
        OS.REMOVE(CSV)


