universe = docker
docker_image = michaelbornholdt/deep_profiler:tf2_v12

accounting_group = COBA
requirements = (Machine == "coba2000.chtc.wisc.edu")

executable = profile.sh
transfer_executable = true
arguments = $(Cluster)

output = out_$(Cluster)
error = err_$(Cluster)
log = log_$(Cluster)

request_cpus = 8
request_gpus = 1
request_memory = 40 GB
request_disk = 10 GB

transfer_input_files = config_profile.json
should_transfer_files = YES


queue
